services:
  - type: web
    name: portfolio
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
